version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  asclepios:
    container_name: asclepios-app
    restart: on-failure
    build: .
    ports:
      - "49100:8080"
    links:
      - mongo
    depends_on:
      - mongo